services:
  postgres:
    image: postgres:17.5-alpine
    container_name: personalblogdb
    restart: on-failure
    ports:
      - "${PG_PORT}:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DBNAME}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql -U ${PG_USER} -d ${PG_DBNAME} -c 'SELECT 1' || exit 1",
        ]
      interval: 10s
      timeout: 2s
      retries: 5
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - pgblogdata:/var/lib/postgresql/data
    networks:
      - blogntwk

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: personalblogpgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
    ports:
      - ${PG_ADMIN_PORT}:80
    volumes:
      - pgadmindata:/var/lib/pgadmin
    networks:
      - blogntwk

volumes:
  pgblogdata:
  pgadmindata:

networks:
  blogntwk:
