CREATE TABLE IF NOT EXISTS categories(
  ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(127) NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);